export const SET_STOREPAGE_TITLE = 'SET_STOREPAGE_TITLE';
export const SET_STOREPAGE_CONTENT = 'SET_STOREPAGE_CONTENT';
export const SET_PRODUCTNAVBAR_ACTIVEITEM = 'SET_PRODUCTNAVBAR_ACTIVEITEM';
export const ADD_CART_ITEM = "ADD_CART_ITEM";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";